### ISSUE TITLE
Curator portal: Manual entry form, Data picker no submit button

### ISSUE THREAD

**Issue by sratcliffe118** [open-covid-data/healthmap-gdo-temp#348]
**Describe the bug**
Submit button is missing from the data picker

**To Reproduce**

**Expected behavior**
Clear call to action to select and submit data from the date picker in the manual entry form

**Screenshots**
<img width="465" alt="Screen Shot 2020-06-25 at 11 35 49 AM" src="https://user-images.githubusercontent.com/63205311/85704495-3f55cc00-b6d8-11ea-93da-e838e496062a.png">

**Comment by attwad** [comment]
Sorry the dev was running an old version that had a white background for those, this is fixed now.
