### ISSUE TITLE
option "no travel history" does not exist

### ISSUE THREAD

**Issue by outbreakprepared** [open-covid-data/healthmap-gdo-temp#388]
**Is your feature request related to a problem? Please describe.**
I would like to have an option to say "no reported travel history"

This is different to NA. I was inputting the recent case from Beijing and it said that the first reported case had no reported travel history indicating that someone else must have brought COVID back into Beijing.

Another used case that I have seen a lot is when governments report 'locally acquired' in the case description which translates into 'no reported travel'

**Describe the solution you'd like**

ad option to say: no reported travel history. include a little Information button saying: only if stated in report.

**Comment by allysonjp715** [comment]
This was fixed today by https://github.com/open-covid-data/healthmap-gdo-temp/pull/385
Will be updated in dev in next push.
