### ISSUE TITLE
Define API to provide authenticated curator information to data service

### ISSUE THREAD

**Issue by attwad** [open-covid-data/healthmap-gdo-temp#394]
We need to define an API for the curator service to pass down the authentication details of the curator talking to it to the data service so that revisionMetadata can be set properly.

Notably right now it is impossible to increment the `revisionMetadata.revisionNumber` or set the `revisionMetadata.updateMetadata` field properly.

**Strawman proposal:**

- data service accepts a new `curator_email` field in the request body of create/update/upsert requests.
- curator service drops any `revisionMetadata` that clients send to it (to not trust them) and fills the `curator_email` field when talking to the data service based on the currently authenticated user.
- data service can then fetch the case, update the `revisionMetadata` accordingly, perform the udpate/upsert/create with the proper `curator` and `date` fields set in the `revisionMetadata.(creationMetadata|updateMetadata)` fields.

**Comment by khmoran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dataserver should populate (most) version data](https://trello.com/c/X0icPhIz/263-dataserver-should-populate-most-version-data)
