### ISSUE TITLE
Calendar picker enhancement

### ISSUE THREAD

**Issue by sratcliffe118** [open-covid-data/healthmap-gdo-temp#427]
User has to scroll backwards multiple times unnecessarily to access dates, which can be a couple of months previously.

Enhancement: allow quick back selection of drop down month and year to allow quick navigate to the date

**Comment by attwad** [comment]
FWIW we're using the standard material design date picker
https://material.io/components/pickers
for which I don't see any way to get a drop down of months (year is already possible, just click on the year).

Have you noticed the user can also just type in the date without relying on the popup? I suspect this is the most efficient way for a past date.

![image](https://user-images.githubusercontent.com/1255432/86370691-540a0500-bc80-11ea-9350-84a674b8a9b5.png)

**Comment by allysonjp715** [comment]
Yes we can't get the dropdown as you are proposing, but I've just sent out a PR to have all date pickers show the confirmation date on opening, which should help minimize scrolling needs.

**Comment by sratcliffe118** [comment]
Sounds good, thanks!

Thanks,

Stephen



<https://sites.google.com/a/google.com/gps-email-signature/home/Google_Signature4.png?attredirects=0>

*  •  **Stephen Ratcliffe*

*  • * Google Pay, Product Manager

*  •  *sratcliffe@google.com

  •  Google, Inc.



*If you received this communication by mistake, please don't forward it to
anyone else (it may contain confidential or privileged information), please
erase all copies of it, including all attachments, and please let the
sender know it went to the wrong person. Thanks.*
