### ISSUE TITLE
Occupation Drop down options: Add more healthcare role options

### ISSUE THREAD

**Issue by sratcliffe118** [open-covid-data/healthmap-gdo-temp#440]
Add more detailed healthcare option roles

**Comment by outbreakprepared** [comment]
Healthcare worker

**Comment by lagood1** [comment]
ER worker

**Comment by sratcliffe118** [comment]
Adding new option to the occupation drop down list

**Comment by axmb** [comment]
Do we want both "Healthcare worker" and "ER Healthcare worker" added?

If so, do we want to phrase it as such, or do we want "Healthcare worker" and "Healthcare worker (ER)"?

**Comment by lagood1** [comment]
@axmb Just Healthcare worker is fine. Decided for now to not get too specific

**Comment by axmb** [comment]
Sounds good. That's been added in #441 and should be live in dev.
