### ISSUE TITLE
Line list case successful entered UX

### ISSUE THREAD

**Issue by sratcliffe118** [open-covid-data/healthmap-gdo-temp#448]
UX design and copy when a line list case is successfully entered to G.H List
![Screen Shot 2020-07-06 at 2 30 29 PM](https://user-images.githubusercontent.com/63205311/86598617-4496fe80-bf95-11ea-88c8-2214f62528a0.png)

**Comment by shroothless** [comment]
Can this message show up in the list view above the table after the submission? The create new case modal should close when the user hits submit.  

![image](https://user-images.githubusercontent.com/67452108/86986077-c25b3580-c160-11ea-971e-2a2c247daf20.png)

**Comment by allysonjp715** [comment]
Thanks, will track the work in #449
