### ISSUE TITLE
Race/Ethnicity distinctions as per US OMB classification schema

### ISSUE THREAD

**Issue by beoutbreakprepared** [open-covid-data/healthmap-gdo-temp#458]
Add a more robust schema for race and ethnicity to reflect US official classifications

https://www.census.gov/topics/population/race/about.html#:~:text=OMB%20requires%20five%20minimum%20categories,Hawaiian%20or%20Other%20Pacific%20Islander.

https://www.census.gov/mso/www/training/pdf/race-ethnicity-onepager.pdf

NOTE: This is a very US-centric focus; we should discuss a more robust way to allow for other schema to be integrated from across the globe

**Comment by allysonjp715** [comment]
Yes we were planning on having a larger discussion on defining race/ethnicity options as this is very tricky to encompass world-wide considerations.

**Comment by sratcliffe118** [comment]
Moritz,
There was an AI to have a wider discussion on this topic, do we have the latest on that?
