### ISSUE TITLE
how do we currently accommodate for example age >60 

### ISSUE THREAD

**Issue by outbreakprepared** [open-covid-data/healthmap-gdo-temp#459]
If data provided says >60. How do we enable that to be entered unambiguously. For now the only option I see is enter 60 - 120. But that's not ideal.

Option could be to allow to enter min age '>60' and autofill to max age (120)?

**Comment by allysonjp715** [comment]
Would we want to store that in the database as 60-120 age range? We could probably add some help text to the error message.

**Comment by sratcliffe118** [comment]
If it's >60 then i would propose the input would be
Min age: 60
Max age: 120

We do not want to enable too much special casing as that tends to grow quickly out of control and the standard scheme becomes very fragmented :)

We should aim to get the dat reported in a more bound way but handle the edge case gracefully.

WDYT?

**Comment by allysonjp715** [comment]
SG. Do we want to change anything in the UI then @shroothless ?

**Comment by shroothless** [comment]
Agree, on use of autofill. I think an error message should suffice, if the Age Min is completed, and Age Max is not can we trigger an error. "Please enter max age, if none enter 120."

**Comment by allysonjp715** [comment]
I wonder about the copy of "Please enter max age, if none enter 120."

If there was no max age, I would think they should enter the "Age" field rather than the min and max ages. I understand we're trying to address Moritz's case of >60, where it is a range but there is no max specified. Perhaps something like "Max age required. Maximum value is 120" WDYT?

**Comment by sratcliffe118** [comment]
Max age required. Maximum value is 120" WDYT?
I think this makes sense

Thanks,

Stephen



<https://sites.google.com/a/google.com/gps-email-signature/home/Google_Signature4.png?attredirects=0>

*  •  **Stephen Ratcliffe*

*  • * Google Pay, Product Manager

*  •  *sratcliffe@google.com

  •  Google, Inc.



*If you received this communication by mistake, please don't forward it to
anyone else (it may contain confidential or privileged information), please
erase all copies of it, including all attachments, and please let the
sender know it went to the wrong person. Thanks.*

**Comment by khmoran** [comment]
Can we leave the min or max out if it's an open ended range?

**Comment by sratcliffe118** [comment]
Would rather stick to a pattern where 65-120 is used as a 65+ pattern by
the users of the data. If we leave it open ended it could lead to bad or
incomplete data and age is a key demographic data point

Thanks,

Stephen



<https://sites.google.com/a/google.com/gps-email-signature/home/Google_Signature4.png?attredirects=0>

*  •  **Stephen Ratcliffe*

*  • * Google Pay, Product Manager

*  •  *sratcliffe@google.com

  •  Google, Inc.



*If you received this communication by mistake, please don't forward it to
anyone else (it may contain confidential or privileged information), please
erase all copies of it, including all attachments, and please let the
sender know it went to the wrong person. Thanks.*
