### ISSUE TITLE
Line List - Page is not responsive to window size

### ISSUE THREAD

**Issue by acansler** [open-covid-data/healthmap-gdo-temp#467]
The table does not respond to changes in window size, requiring users to scroll extensively to see the table contents.

**To Reproduce**
1. Load Page
2. Scroll right

**Expected behavior**
Table automatically conforms to changes in window size?

**Comment by allysonjp715** [comment]
Also fixed in #476

The table wrapper (title, search bar, pagination options) is now according to window size and has an inner scroll for seeing all columns.
