### ISSUE TITLE
Line List - Search field hidden when left nav is open

### ISSUE THREAD

**Issue by acansler** [open-covid-data/healthmap-gdo-temp#468]
**Describe the bug**
When the left hand nav is in an opened state, the search field on the right is moved over, obscuring the field. 

**To Reproduce**
1. Open left hand nav

**Expected behavior**
Search field stays in place

**Screenshots**
<img width="1430" alt="Screen Shot 2020-07-08 at 2 40 08 PM" src="https://user-images.githubusercontent.com/13242399/86957729-23ffad80-c129-11ea-867e-ec1c85b612c4.png">

**Comment by allysonjp715** [comment]
This was fixed in #476
