### ISSUE TITLE
Location field "No Options" drop down confusing

### ISSUE THREAD

**Issue by acansler** [open-covid-data/healthmap-gdo-temp#469]
**Describe the bug**
The moment a user clicks the field in "Location", they are immediately met with a drop down that says "No Options", which is counterintuitive and potentially confusing. 

**To Reproduce**
1. Go to "Location" section
2. Click on field

**Expected behavior**
It could either be empty, or show an example like "ex: Lyons, France", thus making clear to users it's open form field and expects text entry of a location

**Screenshots**
<img width="612" alt="Screen Shot 2020-07-08 at 2 49 16 PM" src="https://user-images.githubusercontent.com/13242399/86958762-a76dce80-c12a-11ea-956c-72754b96bb14.png">

**Comment by attwad** [comment]
I changed that to "No locations" yesterday, I think we can make it "No locations, type to search" or something like that to make it clearer.
