### ISSUE TITLE
Logic issues on date entry for multiple fields

### ISSUE THREAD

**Issue by acansler** [open-covid-data/healthmap-gdo-temp#471]
**Describe the bug**
Currently, there are no rules that would stop or limit "impossible" situations when entering dates for certain events. For example, it is possible to have a case that dies on July 1st, is admitted to the hospital on July 8th, and develops symptoms on July 16th. 

**To Reproduce**
1. Go to Events section
2. Enter in dates for various impossible scenarios.

**Expected behavior**
Built in logic, for a few of these scenarios that would be blocked, or generate a warning message. 

**Note**
While I'm listing this as a "nice to have", in terms of instilling confidence in the tool and our proposed standardization, this does seem important.

**Comment by allysonjp715** [comment]
What restrictions do we want to apply here? The possible events are:
- Case confirmation
- Onset of symptoms
- first clinical consultation
- date of self isolation
- hospital admission date
- admitted to ICU
- outcome

Some restrictions that make sense to me:
- All dates earlier than outcome date
- onset of symptoms before all dates except case confirmation

The second one I'm more wary on than the first. WDYT? Any others?

**Comment by sratcliffe118** [comment]
I would go with the following restrictions / rules
1. No dates earlier than case confirmation. Note they can be on the same date as case confirmation but not earlier.
2.All dates earlier than outcome date

Technical you could be confirmed a case with no symptoms via a test and then symptoms develop after, so I would not put any restrictions around this,

**Comment by allysonjp715** [comment]
> 1. No dates earlier than case confirmation. 

I think there are quite a few dates that could happen before case confirmation: onset of symptoms, first clinical consultation, date of self isolation, potentially even the hospital cases if they do the confirmation after the case gets to the hospital.

So maybe it should just be the "All dates earlier than outcome date" restriction?

**Comment by sratcliffe118** [comment]
Good point.
So maybe it should just be the "All dates earlier than outcome date"
restriction? *ack let's have that as the rule.*



Thanks,

Stephen



<https://sites.google.com/a/google.com/gps-email-signature/home/Google_Signature4.png?attredirects=0>

*  •  **Stephen Ratcliffe*

*  • * Google Pay, Product Manager

*  •  *sratcliffe@google.com

  •  Google, Inc.



*If you received this communication by mistake, please don't forward it to
anyone else (it may contain confidential or privileged information), please
erase all copies of it, including all attachments, and please let the
sender know it went to the wrong person. Thanks.*

**Comment by sratcliffe118** [comment]
Interesting insight from early in the pandemic and data that relates to dates. Some cases were admitted to hospital prior to being a covid-19 confirmed case i.e. admitted for breathing difficulties and then some time after being confirmed as a covid-19 case. This means that hospital admission can be before a confirmed case date

**Comment by allysonjp715** [comment]
As per slack discussion, there could also be a case with a "Recovered" outcome that wasn't confirmed with a test until after recovery. I don't think there are any restrictions we could put here that would fit 100% of cases, so going to close this out. Feel free to reopen if anyone disagrees!
