### ISSUE TITLE
Batched UX Behaviour Bugs

### ISSUE THREAD

**Issue by shroothless** [open-covid-data/healthmap-gdo-temp#475]
**Describe the bug**
Multiple UX Behaviour Bugs

**To Reproduce**
Noted in deck

**Expected behavior**
https://docs.google.com/presentation/d/1Fg-UYsIB8oq03-VIHR0CP8G6ym02HxjCpyDcroheFzc/edit?usp=sharing

**Screenshots**
Noted in deck

**Environment (please complete the following information):**
 - OS: OS Mojave
 - Browser Chrome

**Comment by allysonjp715** [comment]
Thanks for filing Shru! I'll post updates in the deck as things are fixed.

**Comment by allysonjp715** [comment]
The only bug left in the deck is adding the tooltips to the sections which is blocked on copy. @shroothless who created the copy for the fields? Could they also add some for the sections? Thanks!

**Comment by allysonjp715** [comment]
I see what I asked for is covered in #562. I'll close this bug out and track there. Feel free to reopen or create another bug for more UX issues.
