### ISSUE TITLE
Bulk CSV ingestion: Admin level 2 data selecting specific road location 

### ISSUE THREAD

**Issue by sratcliffe118** [open-covid-data/healthmap-gdo-temp#530]
Steps to recreate:
1. Adding Florida data which provide location data to county level
2. Add county information to level 3 data: Broward
3. Populates Broward road, jacksonville in the line list entry
See attached

Expected: Admin level 3 should be county, city or town level, should not go down to specific road depth

![Screen Shot 2020-07-13 at 1 19 52 PM](https://user-images.githubusercontent.com/63205311/87303762-9565a480-c50b-11ea-90b4-3b5fc9419923.png)

**Comment by sratcliffe118** [comment]
Another example is case: 5f0c8630a17f74e5a82fb77b
This admin level 3 data was: CORONEL FABRICIANO/TIMOTEO
The location added to the case: Rua Coronel Fabriciano, Centro Sul, Timóteo - Minas Gerais, 35182, Brazil

**Comment by axmb** [comment]
Thoughts on the results:

For Florida, I think that's a subset of the existing issue around US county identification.

Brazil is somewhat more complicated. To start, that admin3 example data seems to be compound -- Coronel Fabriciano and Timóteo are both municipalities. So I suppose the slash indicates they're joint reporting, or the data is from one of those two locations. For that data, I think we should be entering:

country: Brazil
admin1: Minas Gerais
admin2: Valo do Aço
admin3: Either blank (CF and Timóteo are two of four municipalities in VofA), Coronel Fabriciano, or Timóteo. Granted this field isn't in the bulk format, yet (I'll add it so we can do this kind of testing).

Thoughts on fixes:

We can't "force" the geocoding resolution until the county bug is resolved. If we do, we get 404 for queries like "Broward, Florida, United States."

Do we want to leave a P1 here to limit geocoding resolution, blocked on figuring out our issue with counties?

**Comment by axmb** [comment]
I've added an option to tweak the way we invoke the mapbox API (see the above two PRs).

Does the behavior I've gif'd in #561 seem reasonable?

(Separately, I've documented that `admin3` can be supplied as a field to bulk upload.)

**Comment by sratcliffe118** [comment]
Alex, reviewed and this approach LGTM

Think this example highlights that no matter how automated we make the process, as the data is reported in a fragmented way curators will still be required to make some judgement calls and data manipulation before bulk uploading.
