### ISSUE TITLE
Update UX of source entry

### ISSUE THREAD

**Issue by sratcliffe118** [open-covid-data/healthmap-gdo-temp#531]
Adding a new source flow. Once a URL has been added in the bulk upload or new line list entry screen and select + a new screen appears. Current flow is confusing in 2 areas:

1. The URL field goes into the name field, the 2 should be separate and not run into each other
2. The cursor should automatically move to name when the dialogue pops up so the name can be entered. Currently the cursor remains in the URL field when dialogue opens, this is confusing and results in additions being made to the url by mistake.

Attached screenshot 
![Screen Shot 2020-07-13 at 1 23 18 PM](https://user-images.githubusercontent.com/63205311/87304260-7582b080-c50c-11ea-9eee-e13f1c2fc633.png)

**Comment by shroothless** [comment]
Update: Do not trigger a dialog for a new source. Add a new field under URL titled "Source name" that is required.

**Comment by allysonjp715** [comment]
Latest UX:

![Screen Shot 2020-07-14 at 12 21 40 PM](https://user-images.githubusercontent.com/30459667/87420144-a4f8f200-c5cc-11ea-8aa4-2c7ac01a5c4d.png)

**Comment by sratcliffe118** [comment]
Suggest we add the copy for the source reference name @shroothless how do you see this appearing the UI
Enter the name of the entity that has provided the data e.g. Brazil Ministry of Health
