### ISSUE TITLE
Data source link in list takes you to a blank case

### ISSUE THREAD

**Issue by sratcliffe118** [open-covid-data/healthmap-gdo-temp#533]
Clicking on the data source link in the line list case (see screen shot) takes you to a blank line list case, not the data source information.

![Screen Shot 2020-07-13 at 2 18 41 PM](https://user-images.githubusercontent.com/63205311/87308978-e5e10000-c513-11ea-87a4-7a220af44f0f.png)

**Comment by axmb** [comment]
The case `caseReference.sourceUrl` value is supplied directly to the furnish that link. If the sourceUrl doesn't include a protocol (`http://` or `https://`), it's interpreted as a relative link, and you're sent to `$currentURL/$souceURL`.
