### ISSUE TITLE
Bulk CSV upload: Details of # of line list entries created upon successful upload

### ISSUE THREAD

**Issue by sratcliffe118** [open-covid-data/healthmap-gdo-temp#539]
Currently when a bulk CSV is upload a message it provided indicating if the upload was a success, or if there was an issue which prevented upload. 

Request for a feature to detail the number of line list cases when there has been a successful upload, so that this can be checked against the number the curator was expecting to be created. Current process requires counting the new line list entries which is prone to error and a slow and inefficient use of a curators time. 

AsK;
P0 - Indication of the number of line list cases created by the CSV upload 
P1 - Link to the line list cases created (this could be in the form of a link to the line list with the search criteria set to only show the line list cases uploaded from the CSV the curator has just uploaded

**Comment by axmb** [comment]
I expect we'll use pretty similar functionality to what @allysonjp715 is looking at for #449. That's ~the current proposed UX for bulk, too. As a stopgap, I'll quickly add the P0 aspect to the upload form.

**Comment by sratcliffe118** [comment]
SGTM,thanks @axmb

**Comment by axmb** [comment]
Spec'd UX was added in #601.
