### ISSUE TITLE
Manual Line List Entry Does Not Submit

### ISSUE THREAD

**Issue by dakrownie** [open-covid-data/healthmap-gdo-temp#545]
**Describe the bug**

**To Reproduce**
1. Go to the [Canada Line List Data](https://docs.google.com/spreadsheets/d/1D6okqtBS3S2NRC7GFVHzaZ67DuTw7LX49-fqSLwJyeo/edit#gid=942958991)
2. Fill out provided information 'Source', 'Sex', 'Age', 'Location', 'Event Dates', 'Travel History' ans 'Travel Location'  
3. Click on 'Submit Case'

**Expected behavior**
I expected the line list to submit in the event that not all fields are filled in.

**Screenshots**
![image](https://user-images.githubusercontent.com/33044735/87350911-d89a3480-c558-11ea-98f6-7a4fbbdc6748.jpeg)

**Environment (please complete the following information):**
 - OS: [Chrome OS]
 - Browser [Chrome]
 - Version [Version 83.0.4103.119(Official Build) (64-bit)]

**Additional context**

**Comment by allysonjp715** [comment]
@dakrownie would you be able to copy/paste the error message as a comment here?

**Comment by dakrownie** [comment]
Created and submitted successfully.
