### ISSUE TITLE
Bulk CSV upload slow for files with many rows

### ISSUE THREAD

**Issue by sratcliffe118** [open-covid-data/healthmap-gdo-temp#571]
Attempt to bulk upload file CSV and and seeing this error

<img width="547" alt="Screen Shot 2020-07-16 at 5 07 46 PM" src="https://user-images.githubusercontent.com/63205311/87695068-ee8d3c80-c786-11ea-859c-8886d785110c.png">

**Comment by axmb** [comment]
It's working, but it's working rather slowly. I think there are two issues to address, here:

1. There needs to be a progress indicator (#573).
2. Upload of large files (the one in question was ~40k rows) _should_ be faster. I'll repurpose this issue for that.

**Comment by axmb** [comment]
Retroactively tagging #584, which is the first change to speed this up.
