### ISSUE TITLE
Manual entry is rejected if client time (Date.now()) is ahead of data service time (Date.now())

### ISSUE THREAD

**Issue by axmb** [open-covid-data/healthmap-gdo-temp#574]
**Describe the bug**
Manual entry is rejected if client time (Date.now()) is ahead of data service time (Date.now()).

**To Reproduce**
I can't repro, but there's a recording (soon) available for the curator UXR session in which this came up. This error message won't be visible, but I cross-checked against our cluster logs:

```
data: 'Case validation failed: revisionMetadata.creationMetadata.date: Path `date` (Thu Jul 16 2020 16:40:51 GMT+0000 (Coordinated Universal Time)) is after maximum allowed value (Date.now())., revisionMetadata.creationMetadata: Validation failed: date: Path `date` (Thu Jul 16 2020 16:40:51 GMT+0000 (Coordinated Universal Time)) is after maximum allowed value (Date.now())., revisionMetadata: Validation failed: creationMetadata.date: Path `date` (Thu Jul 16 2020 16:40:51 GMT+0000 (Coordinated Universal Time)) is after maximum allowed value (Date.now())., creationMetadata: Validation failed: date: Path `date` (Thu Jul 16 2020 16:40:51 GMT+0000 (Coordinated Universal Time)) is after maximum allowed value (Date.now()).'
```

**Expected behavior**
New cases shouldn't be susceptible to this time of error.

Relatedly, there should have been a better error message on the client. The message just listed the code (422) -- it should be treated and presented as 500 (~"System error"). The user wasn't sure whether it was a system issue or their entered info was somehow invalid.

**Environment (please complete the following information):**
 - OS: Unsure -- probably either Windows or CrOS.
 - Browser: Chrome
 - Version: Unsure

**Comment by axmb** [comment]
Bizarrely, this reoccurred (consistently) in today's UXR session. Logs excerpt is ~identical.

**Comment by khmoran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dataserver should populate (most) version data](https://trello.com/c/X0icPhIz/263-dataserver-should-populate-most-version-data)
