### ISSUE TITLE
Number of records in the Line list view increases as move through tabbed pages

### ISSUE THREAD

**Issue by sratcliffe118** [open-covid-data/healthmap-gdo-temp#578]
Bug: The total number of records based on the search increase as you go through the tabbed pages
![Screen Shot 2020-07-16 at 8 34 38 PM](https://user-images.githubusercontent.com/63205311/87714618-ed1e3d00-c7a3-11ea-8ccb-2d58aa3b7dd8.png)

Steps to recreate
1. Search by the keyword: Scotland
2. Go to the bottom of the line list view
3. Select 100 rows per view
4. Note the number of records meeting search criteria (bottom right)
5. Tab to the next screen
6. The number of records in the bottom right increases

**Comment by allysonjp715** [comment]
@sratcliffe118  Which environment are you doing this in?

I just reproduced the steps in dev and couldn't reproduce the issue.

**Comment by dakrownie** [comment]
@sratcliffe118 I assigned this to you so you'll see it when you get back. Allyson is not able to reproduce the issue.

**Comment by sratcliffe118** [comment]
This was in Dev, tried again and couldn't reproduce it. Closing
