### ISSUE TITLE
modal popup for new case not dismissed on history.back()

### ISSUE THREAD

**Issue by attwad** [open-covid-data/healthmap-gdo-temp#589]
**Describe the bug**
Pressing back when modal popup of new case is shown should dismiss the modal, instead the page behind it goes back.

**To Reproduce**
1. Go to dev-curator.ghdsi.org
2. Click on linelist to go to /cases
3. Click on Create New -> Line list Case
4. Press back

**Expected behavior**
The modal disappears and we're back /cases.
Instead the page behind it goes to /

**Comment by attwad** [comment]
Also if we can fix the fact that the /cases/new URL was lost when moving to the modal dialog that'd be great, there's no way to link to a new case or to open the app directly on the modal dialog.
I don't know how this got implemented but when the modal popup is shown we should push /cases/new to the URL history, and if we go to that URL it should show the dialog also.

**Comment by allysonjp715** [comment]
Fixed by https://github.com/open-covid-data/healthmap-gdo-temp/commit/c4d18e4ccdf674bcfb11f7328b7fa3a7693b57cf which accidentally wasn't PRed
