### ISSUE TITLE
Start adding tooltips to the various case form fields

### ISSUE THREAD

**Issue by attwad** [open-covid-data/healthmap-gdo-temp#625]
**Is your feature request related to a problem? Please describe.**
Was mentioned a few times during the UX review, we can start adding a few tooltips here and there to make it obvious what some things are meant to be.

https://material-ui.com/components/tooltips/

![image](https://user-images.githubusercontent.com/1255432/88517719-97416480-cfef-11ea-9963-45d385a02bde.png)

**Comment by allysonjp715** [comment]
Duplicate of #562
Code is in place once copy is written: https://github.com/open-covid-data/healthmap-gdo-temp/blob/main/verification/curator-service/ui/src/components/common-form-fields/FieldTitle.tsx

**Comment by attwad** [comment]
ohh nice :) thanks
